More Correction

diff --git a/0x12-web_stack_debugging_2/0-iamsomeoneelse b/0x12-web_stack_debugging_2/0-iamsomeoneelse
--- a/0x12-web_stack_debugging_2/0-iamsomeoneelse
+++ b/0x12-web_stack_debugging_2/0-iamsomeoneelse
@@ -1,9 +1,31 @@
 #!/usr/bin/env bash
-# Check if the user argument is provided
-if [ -z "$1" ]; then
+
+# Function to display usage information
+function display_usage() {
   echo "Usage: $0 <username>"
+}
+
+# Check if the script is run with sudo
+if [ "$(id -u)" -ne 0 ]; then
+  echo "This script requires superuser privileges. Please run it with sudo."
+  exit 1
+fi
+
+# Check if a username argument is provided
+if [ -z "$1" ]; then
+  echo "Error: Username argument is missing."
+  display_usage
+  exit 1
+fi
+
+username="$1"
+
+# Check if the user exists
+if ! id "$username" &>/dev/null; then
+  echo "Error: User '$username' does not exist."
   exit 1
 fi
 
 # Run the "whoami" command as the specified user
-sudo -u "$1" whoami
+sudo -u "$username" whoami
+
